### ISSUE TITLE
Replace invalid characters in the report

### ISSUE THREAD

**Issue by RafalSkorka** [davidparsson/junit-report-builder#20]
I've noticed that when the xmlbuilder is created it sets additional option called `allowSurrogateChars`. However, checking the [builder options](https://github.com/oozcitak/xmlbuilder-js/wiki/Builder-Options) it does not exist. The result is the reports could contain invalid XML characters.
Could you update the code so it sets `invalidCharReplacement: ''` instead?

**Comment by davidparsson** [comment]
The package depends on  [`xmlbuilder@^10.0.0`](https://github.com/davidparsson/junit-report-builder/blob/master/package.json#L42). Could it be the case that this old version has this option, but that it has been removed in newer versions?

**Comment by RafalSkorka** [comment]
Yes, that's how it looks to me, searching for allowSurrogateChars in that repo returns only some closed issues (latest from 2017) but not any source code.

**Comment by davidparsson** [comment]
Fixed on master, I'll release 3.0.0 as soon as possible but I ran into issues authenticating and now I'm "auth rate limited". 😑

**Comment by davidparsson** [comment]
[`3.0.0`](https://www.npmjs.com/package/junit-report-builder/v/3.0.0) is released
