### ISSUE TITLE
Attachment screenshot when test fails

### ISSUE THREAD

**Issue by Redinbox** [davidparsson/junit-report-builder#37]
Hello,
we started using webdriverIO, is there any way to add screenshot as an attachment ?
can you share a solution to add screenshot?

**Comment by davidparsson** [comment]
How would that be represented in the XML?

I found nothing about attachments during a quick read-through of [the spec](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd).

If you want support for the [JUnit Attachments plugin](https://plugins.jenkins.io/junit-attachments/) I believe just adding the output in the expected format to standard output.

**Comment by davidparsson** [comment]
Just to clarify, are you asking how to use WebdriverIO to save screenshots, or are you asking on behalf of WebdriverIO to implement new features there?

**Comment by Redinbox** [comment]
Sorry, 
Let me explain what I am doing
Am using wdio-junit - reporter, but unfortunately no option to attach screen shot when ever test fails,
While searching I found this repo here,
My requirement is I want attach screen shot and when I ci on azure pipeline, it shud appears

**Comment by davidparsson** [comment]
All right. I believe that your request is out of scope for this tool, as this only proves a simple api to create working JUnit XML files. Attaching screenshots does not seem to be included in the spec, nor does it seem to require any special format.

Perhaps these resources might help you:
- https://webdriver.io/docs/api/browser/saveScreenshot/
- https://stackoverflow.com/questions/59511868/can-we-add-screenshots-as-an-attachment-to-the-test-result-in-azure-pipeline

**Comment by davidparsson** [comment]
Feel free to reopen if it turns out I'm wrong.
