### ISSUE TITLE
Would you mind releasing a new version of this package?

### ISSUE THREAD

**Issue by tbroadley** [davidparsson/junit-report-builder#42]
Hello! Thanks for the great package.

I see that this repo's main branch contains changes that aren't part of any version of the package on NPM. In particular, I see there was a change to bump the date-format dependency from 0.0.2 to 4.0.3. That'd help me resolve https://github.com/tbroadley/spellchecker-cli/issues/98.

Would it be possible to create a new release of this package on NPM?

I recognize that I could change probably my package to depend directly on a specific commit in this repo, but would rather stick to using dependencies from NPM.

**Comment by davidparsson** [comment]
Yes, I'll try to get that done today.

**Comment by davidparsson** [comment]
[3.0.1](https://github.com/davidparsson/junit-report-builder/releases/tag/3.0.1) was published just now.

**Comment by tbroadley** [comment]
Thank you very much!
