### ISSUE TITLE
Escaping in attributes

### ISSUE THREAD

**Issue by antonio-paunovic** [davidparsson/junit-report-builder#5]
Hello,
I've used https://github.com/webdriverio/wdio-junit-reporter library to generate some selenium test results and got something that looks like invalid xml file.
Here is a line from it:
`<error message="element ("pre") still not visible after 10000ms"/>`

 More specifically, in ` ("pre")` quotes should be escaped. 
Is there an option to make it happen?

**Comment by davidparsson** [comment]
Thanks for reporting! There is no configuration for that, it's a bug. It could possibly be resolved by updating the dependency `xmlbuilder`.

**Comment by antonio-paunovic** [comment]
Ok, thanks.
I'll standby.

**Comment by davidparsson** [comment]
Ok, so I created a test that should have reproduced this, but for me it works: https://github.com/davidparsson/junit-report-builder/commit/8c565f9c68125a5e57598a4a764f08027e4cfc3f, [commit build](https://travis-ci.org/davidparsson/junit-report-builder/builds/341841664)

What version of `xmlbuilder` are you using? I'm on `xmlbuilder@2.6.5`.

**Comment by davidparsson** [comment]
That's weird. My test passes locally even after downgrading to that version.

**Comment by antonio-paunovic** [comment]
Turns out it was internal problem. It seems file was dragged through browser and qoutes were represented as actual quotes. 
Sorry for useless distractions, I'm grateful for assistance!

**Comment by davidparsson** [comment]
No worries, I'm glad it worked out.
