### ISSUE TITLE
4.0.0 can't work!

### ISSUE THREAD

**Issue by HHN0609** [davidparsson/junit-report-builder#72]
When I run the code that copied from the readme, it throws error. And my package's version is 4.0.0. 3.2.1 is fine.
```js
var suite = builder.testSuite().name('My suite');
                    ^
TypeError: builder.testSuite is not a function
```

**Comment by HHN0609** [comment]
xmlbuilder updated 4 days ago, maybe this issue is from xmlbuilder.

**Comment by davidparsson** [comment]
Thanks for reporting! This is a known issue, with more details in #71.

During the internal conversation to typescript, the public API was accidentally changed. Work on a fix is ongoing. Since 4.0.0 contains no new functionality, only types, I recommend waiting for the next release before updating.

**Comment by davidparsson** [comment]
@HHN0609, 4.0.1 is now released and should fix for this. Please reopen if that is not the case.

**Comment by HHN0609** [comment]
> @HHN0609, 4.0.1 is now released and should fix for this. Please reopen if that is not the case.

thanks！
