### ISSUE TITLE
4.0.1 seems to be a semver major-version breaking change for the same reason 4.0.0 was

### ISSUE THREAD

**Issue by DavidAnson** [davidparsson/junit-report-builder#75]
CommonJS callers who had to add `.default` when updating to 4.0.0 will need to remove it (according to my CI run from the relevant Dependabot PR) in 4.0.1. If so, then 4.0.1 should instead be version 5.0.0 as it is neither patch nor minor per semver guidance.

**Comment by davidparsson** [comment]
Thanks for reporting.

This was not intended, and again, my lack of time and understandning caused problems. I'm sorry for the inconvenience. The API change in 4.0.0 was unintentional, and I (incorrectly) assumed that this completely broke CommonJS support, but apparently this was not the case.

I'll deprecate 4.0.1 and release 5.0.0 in its place.

**Comment by davidparsson** [comment]
5.0.0 is released.

**Comment by davidparsson** [comment]
I agree! Thanks for reporting!
